apiVersion: v1
kind: Service
metadata:
  name: timeapp-service
spec:
  type: NodePort
  selector:
    app: timeapp
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
      nodePort: 30000  # NodePort can be any available port in the range 30000-32767
